modLoader = "javafml"
loaderVersion = "[9,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "vitra"
version = "${version}"
displayName = "Vitra"
authors = "Vitra Team"
description = '''
High-performance optimization and multi-backend rendering mod for Minecraft
'''
#logoFile = ""

[[dependencies.vitra]]
modId = "neoforge"
type = "required"
versionRange = "[21.8,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vitra]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.8,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vitra]]
modId = "architectury"
type = "required"
versionRange = "[17.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "vitra.mixins.json"
